import type { BadmintonClass, Coach } from "@workspace/api-client-react";

export const fallbackClasses: BadmintonClass[] = [
  {
    id: 1,
    name: "Grassroots - Ages 6-9",
    level: "Beginner",
    description:
      "A playful foundation program that builds movement confidence, basic racket skills, balance, coordination, discipline, and a love for sport.",
    schedule: "Foundation Sessions",
    duration: "Age 6-9 Pathway",
    maxStudents: 16,
    price: 0,
    coachName: "Dayal Core Team",
  },
  {
    id: 2,
    name: "Beginner Track / Prerequisite Class - Ages 9-11",
    level: "Beginner",
    description:
      "A structured entry pathway for young players to learn court movement, grip, basic strokes, rally confidence, and training discipline.",
    schedule: "Prerequisite Track",
    duration: "Age 9-11 Pathway",
    maxStudents: 18,
    price: 0,
    coachName: "Dayal Core Team",
  },
  {
    id: 3,
    name: "Semi-Private (Family & Friends Beginner)",
    level: "Beginner",
    description:
      "Small-group beginner coaching for families and friends who want focused attention while learning together in a comfortable setting.",
    schedule: "Flexible Scheduling",
    duration: "Shared Beginner Sessions",
    maxStudents: 6,
    price: 0,
    coachName: "Beginner Coaching Team",
  },
  {
    id: 4,
    name: "Intermediate Class",
    level: "Intermediate",
    description:
      "Technical development for players ready to improve footwork, stroke quality, rally patterns, tactical awareness, and match confidence.",
    schedule: "Technical Development",
    duration: "Intermediate Track",
    maxStudents: 20,
    price: 0,
    coachName: "Dayal Core Team",
  },
  {
    id: 5,
    name: "Badminton Fitness Class",
    level: "Intermediate",
    description:
      "Badminton-specific fitness focused on agility, endurance, strength, speed, stability, injury resistance, and court-ready conditioning.",
    schedule: "Fitness Blocks",
    duration: "Conditioning Track",
    maxStudents: 20,
    price: 0,
    coachName: "Fitness Support Team",
  },
  {
    id: 6,
    name: "Corporate Class",
    level: "Intermediate",
    description:
      "Energetic badminton sessions for corporate groups, designed for fitness, team bonding, stress relief, and recreational competition.",
    schedule: "Corporate Bookings",
    duration: "Group Session Format",
    maxStudents: 30,
    price: 0,
    coachName: "Corporate Coaching Team",
  },
  {
    id: 7,
    name: "Junior Elite Team - Ages 11-15",
    level: "Advanced",
    description:
      "A competitive pathway for promising juniors with advanced drills, structured assessments, match preparation, and tournament readiness.",
    schedule: "Elite Junior Track",
    duration: "Age 11-15 Pathway",
    maxStudents: 18,
    price: 0,
    coachName: "Elite Coaching Team",
  },
  {
    id: 8,
    name: "Senior Elite Team - Ages 15-19",
    level: "Advanced",
    description:
      "High-performance training for senior juniors targeting stronger technique, tactical maturity, physical readiness, and competition exposure.",
    schedule: "Elite Senior Track",
    duration: "Age 15-19 Pathway",
    maxStudents: 18,
    price: 0,
    coachName: "Elite Coaching Team",
  },
  {
    id: 9,
    name: "Adult / Masters Class",
    level: "Advanced",
    description:
      "Adult and masters coaching for fitness, technical correction, competitive play, and smarter game management.",
    schedule: "Adult Track",
    duration: "Masters Development",
    maxStudents: 20,
    price: 0,
    coachName: "Masters Coaching Team",
  },
  {
    id: 10,
    name: "Pro Team - Ages 19+",
    level: "Elite",
    description:
      "A serious high-performance pathway for players pursuing professional competition, elite exposure, and advanced performance systems.",
    schedule: "Pro Team Training",
    duration: "Age 19+ Pathway",
    maxStudents: 12,
    price: 0,
    coachName: "Dr. Yuva Dayalan",
  },
  {
    id: 11,
    name: "Private Class",
    level: "Elite",
    description:
      "Personalized one-to-one coaching for targeted technical correction, tactical planning, fitness support, and accelerated player development.",
    schedule: "By Appointment",
    duration: "Personal Coaching",
    maxStudents: 1,
    price: 0,
    coachName: "Expert Coach Team",
  },
];

export const fallbackCoaches: Coach[] = [
  {
    id: 1,
    name: "Dr. Yuva Dayalan",
    title: "Founder & Head Coach",
    bio: "Former international badminton player, World Masters Ranking Champion, and holder of 5 Guinness World Records. He leads the academy vision, player pathways, and high-performance coaching standards.",
    specialties: [
      "Program Design",
      "Mixed Doubles",
      "Holistic Fitness",
      "High Performance Oversight",
    ],
    experience: "International career",
    achievements: [
      "5 Guinness World Records",
      "Former trainer of the China badminton team for the 2008 Olympics",
      "Worked with Saina Nehwal and P. V. Sindhu",
      "Current world masters ranking champion",
    ],
    rating: 4.9,
    studentsCount: 320,
  },
  {
    id: 2,
    name: "Xiong Guobao",
    title: "Overseas Mentor & Former World Champion",
    bio: "Former World Champion and internationally respected mentor known for scientific grip training and world-class backhand development.",
    specialties: ["Grip Science", "Singles Mastery", "Elite Mentorship", "World Champion Guidance"],
    experience: "World champion era",
    achievements: [
      "Former world champion",
      "Korea 2023 world masters champion",
      "Mentored Taufiq Hidayat, Lee Chong Wei, and Carolina Marin",
      "Known as the backhand king",
    ],
    rating: 5.0,
    studentsCount: 150,
  },
  {
    id: 3,
    name: "Dr. Kannan Pugazhendi",
    title: "Sports Medicine & Rehabilitation Lead",
    bio: "Heads sports injury management and athlete assessment with experience across Olympic and national teams in multiple sports.",
    specialties: [
      "Sports Medicine",
      "Rehabilitation",
      "Biomechanic Assessment",
      "Injury Prevention",
    ],
    experience: "100,000+ professionals trained",
    achievements: [
      "Headed Indian Olympic team medical support",
      "Worked across cricket, hockey, squash, volleyball, softball, and badminton",
      "Published in Indian Express and The Hindu",
      "Built large-scale professional education programs",
    ],
    rating: 4.9,
    studentsCount: 100,
  },
  {
    id: 4,
    name: "Shiny Surendaran",
    title: "Sports Nutrition & Preventive Health Nutritionist",
    bio: "Provides sports nutrition guidance with experience supporting cricket, squash, kabaddi, and badminton athletes.",
    specialties: [
      "Sports Nutrition",
      "Preventive Health",
      "Athlete Diet Planning",
      "Workshop Delivery",
    ],
    experience: "Multi-sport consulting",
    achievements: [
      "Worked with IPL and TNPL cricketers",
      "Supported Indian squash and badminton athletes",
      "Lecturer in medical education",
      "Conference speaker and workshop trainer",
    ],
    rating: 4.8,
    studentsCount: 120,
  },
  {
    id: 5,
    name: "Dr. T.A. Krishnan",
    title: "Yoga Guru",
    bio: "An 85-year-old traditional lineage yoga guru guiding wellbeing, flexibility, lung capacity, and injury-reduction modules for player health.",
    specialties: ["Yoga", "Flexibility", "Lung Capacity", "Wellbeing"],
    experience: "85+ years legacy",
    achievements: [
      "Academic and curriculum leadership in yoga",
      "Worked with Madras University and Tamil Nadu Sports University",
      "Traditional lineage guru",
      "Heads yoga modules for player wellbeing",
    ],
    rating: 4.9,
    studentsCount: 90,
  },
  {
    id: 6,
    name: "Mrs. Vadhana Moulei",
    title: "Women / Girls Singles Mentor",
    bio: "Former national champion leading girls and women singles training techniques.",
    specialties: ["Women's Singles", "Technique", "Competitive Development", "Mentor Sessions"],
    experience: "Former national champion",
    achievements: [
      "Former national champion",
      "Heads girls singles training",
      "Leads women singles technique sessions",
      "Part of speciality mentor network",
    ],
    rating: 4.8,
    studentsCount: 60,
  },
  {
    id: 7,
    name: "Mrs. Tarnum Parveen",
    title: "Women Doubles & Mixed Doubles Specialist",
    bio: "Former doubles and mixed doubles national-ranked player leading women doubles and mixed doubles modules.",
    specialties: ["Women's Doubles", "Mixed Doubles", "Tactics", "Match Play"],
    experience: "13+ years title-winning background",
    achievements: [
      "Former doubles & mixed doubles national-ranked player",
      "Won Tamil Nadu state title for more than 13 years",
      "Leads women doubles training",
      "Leads mixed doubles development",
    ],
    rating: 4.8,
    studentsCount: 70,
  },
  {
    id: 8,
    name: "Mr. Roy Mathew",
    title: "Doubles Mentor",
    bio: "Former national doubles champion and Asian-ranked player focused on advanced doubles training techniques.",
    specialties: ["Doubles", "Positioning", "Rotation", "Advanced Match Play"],
    experience: "Former national and Asian-ranked competitor",
    achievements: [
      "Former national doubles champion",
      "Asian-ranked player",
      "Heads doubles speciality training",
      "Part of speciality mentor visit program",
    ],
    rating: 4.8,
    studentsCount: 75,
  },
  {
    id: 9,
    name: "Mr. Chandrasekar",
    title: "Singles Mentor",
    bio: "Former national player and ten-time Tamil Nadu champion responsible for singles-oriented development work.",
    specialties: ["Singles", "Tactical Play", "Court Coverage", "Competitive Training"],
    experience: "10-time Tamil Nadu champion",
    achievements: [
      "Former national player",
      "10-time Tamil Nadu champion",
      "Sports officer of RBI",
      "Leads singles speciality techniques",
    ],
    rating: 4.8,
    studentsCount: 80,
  },
  {
    id: 10,
    name: "Kumar Asan",
    title: "Kalari Performance Coach",
    bio: "Heads Kalari programs for speed and wrist power using traditional methods such as Silambam and related movement forms.",
    specialties: ["Kalari", "Speed", "Wrist Power", "Traditional Conditioning"],
    experience: "Traditional Kalari specialist",
    achievements: [
      "Leads Kalari modules",
      "Focus on speed and wrist power",
      "Includes Silambam-based drills",
      "Part of holistic training system",
    ],
    rating: 4.7,
    studentsCount: 65,
  },
  {
    id: 11,
    name: "Mrs. Lakshmi Yuva",
    title: "Overseas Director & Coordination Trainer",
    bio: "Overseas director and coordination trainer using dance and Zumba-based movement to improve reflex and reaction skills through engaging sessions.",
    specialties: ["Coordination", "Dance Movement", "Reflex Training", "Reaction Skills"],
    experience: "Movement and Zumba instruction",
    achievements: [
      "Leads reflex improvement sessions",
      "Movement-based training specialist",
      "Supports fun coordination classes",
      "Part of holistic training schedule",
    ],
    rating: 4.7,
    studentsCount: 85,
  },
  {
    id: 12,
    name: "Mr. Balaji",
    title: "Speed & Endurance Trainer",
    bio: "Former Tamil Nadu 100m and 200m athlete designing workouts for strength, speed, and speed-endurance development.",
    specialties: ["Speed", "Endurance", "Strength", "Conditioning"],
    experience: "Former track athlete and veteran badminton player",
    achievements: [
      "Former Tamil Nadu 100m and 200m athlete",
      "Designs speed-endurance workouts",
      "Supports competitive conditioning",
      "Integrated into athlete development plan",
    ],
    rating: 4.7,
    studentsCount: 85,
  },
];
