import type { BadmintonClass, Coach } from "@workspace/api-client-react";

export const fallbackClasses: BadmintonClass[] = [
  {
    id: 1,
    name: "Daily Senior Coach Execution",
    level: "Beginner",
    description:
      "A senior coach executes the daily morning and evening schedule designed by the Dayal core team for player improvement.",
    schedule: "Morning & Evening Sessions",
    duration: "Daily",
    maxStudents: 45,
    price: 95000,
    coachName: "Dr. Yuva Dayalan",
  },
  {
    id: 2,
    name: "Training Solutions & Workshops",
    level: "Beginner",
    description:
      "Education programs, training solutions, workshops, camps, and championships built to develop budding players toward national and international standards.",
    schedule: "Year-Round",
    duration: "Core Academy Offering",
    maxStudents: 45,
    price: 0,
    coachName: "Dayal Core Team",
  },
  {
    id: 3,
    name: "Skill Assessment Program",
    level: "Beginner",
    description:
      "On-court stroke assessment is conducted every three months, with progress graphs shared with parents and management.",
    schedule: "Every 3 Months",
    duration: "Quarterly Review",
    maxStudents: 45,
    price: 2250,
    coachName: "Dr. Yuva Dayalan",
  },
  {
    id: 4,
    name: "Biomechanic Assessment",
    level: "Intermediate",
    description:
      "Musculoskeletal assessment, posture, power, flexibility, agility, reaction time, and cardio-respiratory fitness evaluation every four months.",
    schedule: "Every 4 Months",
    duration: "Assessment Cycle",
    maxStudents: 45,
    price: 0,
    coachName: "Dr. Kannan Pugazhendi",
  },
  {
    id: 5,
    name: "Sports Medicine & Rehabilitation",
    level: "Intermediate",
    description:
      "Sports injury management and rehabilitation support delivered by an experienced sports medicine team.",
    schedule: "Scheduled Support Sessions",
    duration: "Ongoing Athlete Care",
    maxStudents: 45,
    price: 0,
    coachName: "Dr. Kannan Pugazhendi",
  },
  {
    id: 6,
    name: "Sports Nutrition Guidance",
    level: "Intermediate",
    description:
      "General nutrition advice and preventive sports nutrition guidance for players as part of the academy support structure.",
    schedule: "3 Times / Year",
    duration: "Nutrition Review",
    maxStudents: 45,
    price: 0,
    coachName: "Shiny Surendaran",
  },
  {
    id: 7,
    name: "Speciality Mentor Weekends",
    level: "Intermediate",
    description:
      "National and international mentors visit every 60 days for focused training in singles, doubles, mixed doubles, and women’s events.",
    schedule: "6 Visits Per Year",
    duration: "Weekend Intensive",
    maxStudents: 45,
    price: 0,
    coachName: "Speciality Mentor Team",
  },
  {
    id: 8,
    name: "Girls / Women Singles Training",
    level: "Advanced",
    description:
      "Tailored singles training for girls and women under the guidance of a former national champion.",
    schedule: "Mentor Visit Blocks",
    duration: "Speciality Module",
    maxStudents: 20,
    price: 0,
    coachName: "Vadhana Moulei",
  },
  {
    id: 9,
    name: "Women Doubles & Mixed Doubles",
    level: "Advanced",
    description:
      "Focused doubles and mixed doubles training led by a former doubles and mixed doubles national-ranked player.",
    schedule: "Mentor Visit Blocks",
    duration: "Speciality Module",
    maxStudents: 20,
    price: 0,
    coachName: "Tarnum Parveen",
  },
  {
    id: 10,
    name: "Doubles Speciality Training",
    level: "Advanced",
    description:
      "Advanced doubles technique and match-play specialization delivered by a former national doubles champion and Asian-ranked player.",
    schedule: "Mentor Visit Blocks",
    duration: "Speciality Module",
    maxStudents: 20,
    price: 0,
    coachName: "Roy Mathew",
  },
  {
    id: 11,
    name: "Singles Speciality Training",
    level: "Advanced",
    description:
      "Dedicated singles training methodology led by a former national player and ten-time Tamil Nadu champion.",
    schedule: "Mentor Visit Blocks",
    duration: "Speciality Module",
    maxStudents: 20,
    price: 0,
    coachName: "Chandra Sekar",
  },
  {
    id: 12,
    name: "Holistic Fitness Modules",
    level: "Advanced",
    description:
      "Yoga, Kalari, dance-based coordination, and speed-endurance work are integrated to improve reflex, power, and injury resistance.",
    schedule: "Integrated With Training",
    duration: "Year-Round",
    maxStudents: 45,
    price: 0,
    coachName: "Holistic Support Team",
  },
  {
    id: 13,
    name: "Yoga for Wellbeing & Flexibility",
    level: "Advanced",
    description:
      "Yoga modules focused on lung capacity, flexibility, and injury reduction under a traditional lineage yoga guru.",
    schedule: "2 Visits / Year",
    duration: "Recovery & Mobility",
    maxStudents: 45,
    price: 0,
    coachName: "Dr. T. A. Krishnan",
  },
  {
    id: 14,
    name: "Kalari Speed & Wrist Power",
    level: "Advanced",
    description:
      "Kalari-based development for speed and wrist power, including traditional movement drills and weapon forms.",
    schedule: "2 Visits / Year",
    duration: "Traditional Performance Module",
    maxStudents: 45,
    price: 0,
    coachName: "Kumar Asan",
  },
  {
    id: 15,
    name: "Coordination Training",
    level: "Advanced",
    description:
      "Dance and Zumba-based movement training to improve reflexes, timing, and reaction skills through simple, fun movement patterns.",
    schedule: "Integrated Sessions",
    duration: "Coordination Module",
    maxStudents: 45,
    price: 0,
    coachName: "Mrs Lakshmi",
  },
  {
    id: 16,
    name: "Speed & Endurance Training",
    level: "Advanced",
    description:
      "Workouts designed to improve strength, speed, and speed-endurance for competitive badminton players.",
    schedule: "Integrated Sessions",
    duration: "Conditioning Module",
    maxStudents: 45,
    price: 0,
    coachName: "Mr Balaji",
  },
  {
    id: 17,
    name: "Advanced Training Equipment Program",
    level: "Elite",
    description:
      "Scientific equipment-based development using badminton robots, smart connectors, nozzle cushions, tower connectors, and smart grips.",
    schedule: "Integrated With Daily Training",
    duration: "Technical Development",
    maxStudents: 45,
    price: 0,
    coachName: "Dayal Core Team",
  },
  {
    id: 18,
    name: "Overseas Exposure Camps",
    level: "Advanced",
    description:
      "Players can access advanced overseas training opportunities through academy collaborations in China, Indonesia, and Malaysia.",
    schedule: "Seasonal Camp Windows",
    duration: "Camp Based",
    maxStudents: 20,
    price: 0,
    coachName: "International Partners",
  },
  {
    id: 19,
    name: "Summer Coaching Camps",
    level: "Elite",
    description:
      "Senior coaches can be deputed for special camps and summer camps for stipulated periods at additional cost.",
    schedule: "Seasonal",
    duration: "Camp Format",
    maxStudents: 45,
    price: 0,
    coachName: "Senior Coach Team",
  },
  {
    id: 20,
    name: "Tournament Pathway Support",
    level: "Elite",
    description:
      "Focus on BWF, BAI, SGFI, Khelo India, and TNBA events, with notifications and support for tournament participation.",
    schedule: "As Per Tournament Calendar",
    duration: "Competition Cycle",
    maxStudents: 45,
    price: 0,
    coachName: "Program Oversight Team",
  },
  {
    id: 21,
    name: "Virtual Training Sessions",
    level: "Elite",
    description:
      "Virtual sessions are arranged with senior and overseas coaches whenever specialist training is required.",
    schedule: "On Demand",
    duration: "Remote Mentoring",
    maxStudents: 45,
    price: 0,
    coachName: "World Champion Network",
  },
  {
    id: 22,
    name: "Sponsorship & Player Support",
    level: "Elite",
    description:
      "Outstanding players can be supported with Dayal contracts covering badminton kits, accessories, and sponsorship opportunities.",
    schedule: "Based On Performance",
    duration: "Player Support Pathway",
    maxStudents: 45,
    price: 0,
    coachName: "Dayal Brand Support",
  },
];

export const fallbackCoaches: Coach[] = [
  {
    id: 1,
    name: "Dr. Yuva Dayalan",
    title: "Founder, Former International Player & World Masters Champion",
    bio: "Leads the academy vision, oversees player programs and daily schedules, and brings experience training elite Indian badminton players.",
    specialties: [
      "Program Design",
      "Mixed Doubles",
      "Holistic Fitness",
      "High Performance Oversight",
    ],
    experience: "International career",
    achievements: [
      "5 Guinness World Records",
      "Trainer of China badminton team for the 2008 Olympics",
      "Worked with Saina Nehwal and P. V. Sindhu",
      "Current world masters ranking champion",
    ],
    rating: 4.9,
    studentsCount: 320,
  },
  {
    id: 2,
    name: "Xiong Guobao",
    title: "Mentor & Former World Champion",
    bio: "Guides the academy under a scientific grip approach and brings world-level mentorship across Asia.",
    specialties: ["Grip Science", "Singles Mastery", "Elite Mentorship", "World Champion Guidance"],
    experience: "World champion era",
    achievements: [
      "Former world champion",
      "Korea 2023 world masters champion",
      "Mentored Taufiq Hidayat, Lee Chong Wei, and Carolina Marin",
      "Known as the backhand king",
    ],
    rating: 5.0,
    studentsCount: 150,
  },
  {
    id: 3,
    name: "Dr. Kannan Pugazhendi",
    title: "Sports Medicine & Rehabilitation Lead",
    bio: "Heads sports injury management and athlete assessment with experience across Olympic and national teams in multiple sports.",
    specialties: [
      "Sports Medicine",
      "Rehabilitation",
      "Biomechanic Assessment",
      "Injury Prevention",
    ],
    experience: "100,000+ professionals trained",
    achievements: [
      "Headed Indian Olympic team medical support",
      "Worked across cricket, hockey, squash, volleyball, softball, and badminton",
      "Published in Indian Express and The Hindu",
      "Built large-scale professional education programs",
    ],
    rating: 4.9,
    studentsCount: 100,
  },
  {
    id: 4,
    name: "Shiny Surendaran",
    title: "Sports Nutrition & Preventive Health Nutritionist",
    bio: "Provides sports nutrition guidance with experience supporting cricket, squash, kabaddi, and badminton athletes.",
    specialties: [
      "Sports Nutrition",
      "Preventive Health",
      "Athlete Diet Planning",
      "Workshop Delivery",
    ],
    experience: "Multi-sport consulting",
    achievements: [
      "Worked with IPL and TNPL cricketers",
      "Supported Indian squash and badminton athletes",
      "Lecturer in medical education",
      "Conference speaker and workshop trainer",
    ],
    rating: 4.8,
    studentsCount: 120,
  },
  {
    id: 5,
    name: "Dr. T. A. Krishnan",
    title: "Yoga Guru",
    bio: "Traditional lineage yoga guru leading wellbeing, flexibility, and lung-capacity-focused yoga for injury reduction and athlete health.",
    specialties: ["Yoga", "Flexibility", "Lung Capacity", "Wellbeing"],
    experience: "85+ years legacy",
    achievements: [
      "Academic and curriculum leadership in yoga",
      "Worked with Madras University and Tamil Nadu Sports University",
      "Traditional lineage guru",
      "Heads yoga modules for player wellbeing",
    ],
    rating: 4.9,
    studentsCount: 90,
  },
  {
    id: 6,
    name: "Vadhana Moulei",
    title: "Girls / Women Singles Specialist",
    bio: "Former national champion leading girls and women singles training techniques.",
    specialties: ["Women's Singles", "Technique", "Competitive Development", "Mentor Sessions"],
    experience: "Former national champion",
    achievements: [
      "Former national champion",
      "Heads girls singles training",
      "Leads women singles technique sessions",
      "Part of speciality mentor network",
    ],
    rating: 4.8,
    studentsCount: 60,
  },
  {
    id: 7,
    name: "Tarnum Parveen",
    title: "Women Doubles & Mixed Doubles Specialist",
    bio: "Former doubles and mixed doubles national-ranked player leading women doubles and mixed doubles modules.",
    specialties: ["Women's Doubles", "Mixed Doubles", "Tactics", "Match Play"],
    experience: "13+ years title-winning background",
    achievements: [
      "Former doubles & mixed doubles national-ranked player",
      "Won Tamil Nadu state title for more than 13 years",
      "Leads women doubles training",
      "Leads mixed doubles development",
    ],
    rating: 4.8,
    studentsCount: 70,
  },
  {
    id: 8,
    name: "Roy Mathew",
    title: "Doubles Speciality Coach",
    bio: "Former national doubles champion and Asian-ranked player focused on advanced doubles training techniques.",
    specialties: ["Doubles", "Positioning", "Rotation", "Advanced Match Play"],
    experience: "Former national and Asian-ranked competitor",
    achievements: [
      "Former national doubles champion",
      "Asian-ranked player",
      "Heads doubles speciality training",
      "Part of speciality mentor visit program",
    ],
    rating: 4.8,
    studentsCount: 75,
  },
  {
    id: 9,
    name: "Chandra Sekar",
    title: "Singles Speciality Coach",
    bio: "Former national player and ten-time Tamil Nadu champion responsible for singles-oriented development work.",
    specialties: ["Singles", "Tactical Play", "Court Coverage", "Competitive Training"],
    experience: "10-time Tamil Nadu champion",
    achievements: [
      "Former national player",
      "10-time Tamil Nadu champion",
      "Sports officer of RBI",
      "Leads singles speciality techniques",
    ],
    rating: 4.8,
    studentsCount: 80,
  },
  {
    id: 10,
    name: "Kumar Asan",
    title: "Kalari Performance Coach",
    bio: "Heads Kalari programs for speed and wrist power using traditional methods such as Silambam and related movement forms.",
    specialties: ["Kalari", "Speed", "Wrist Power", "Traditional Conditioning"],
    experience: "Traditional Kalari specialist",
    achievements: [
      "Leads Kalari modules",
      "Focus on speed and wrist power",
      "Includes Silambam-based drills",
      "Part of holistic training system",
    ],
    rating: 4.7,
    studentsCount: 65,
  },
  {
    id: 11,
    name: "Mrs Lakshmi",
    title: "Coordination Trainer",
    bio: "Uses dance and Zumba to improve reflex and reaction skills through fun, movement-based sessions.",
    specialties: ["Coordination", "Dance Movement", "Reflex Training", "Reaction Skills"],
    experience: "Movement and Zumba instruction",
    achievements: [
      "Leads reflex improvement sessions",
      "Movement-based training specialist",
      "Supports fun coordination classes",
      "Part of holistic training schedule",
    ],
    rating: 4.7,
    studentsCount: 85,
  },
  {
    id: 12,
    name: "Mr Balaji",
    title: "Speed & Endurance Trainer",
    bio: "Former Tamil Nadu 100m and 200m athlete designing workouts for strength, speed, and speed-endurance development.",
    specialties: ["Speed", "Endurance", "Strength", "Conditioning"],
    experience: "Former track athlete and veteran badminton player",
    achievements: [
      "Former Tamil Nadu 100m and 200m athlete",
      "Designs speed-endurance workouts",
      "Supports competitive conditioning",
      "Integrated into athlete development plan",
    ],
    rating: 4.7,
    studentsCount: 85,
  },
];
